### ISSUE TITLE
support for Python in cloud pebble IDE

### ISSUE THREAD

**Issue by denfromufa** [pebble/pypkjs#2]

**Comment by Katharine** [comment]
I don't understand; what are you asking for?

**Comment by denfromufa** [comment]
Is it possible to use cloudpebble.net/ide/ and develop in Python instead of C/Javascript?

**Comment by Katharine** [comment]
It is not; Pebble does not (and, realistically, probably cannot) provide a python interpreter. Sorry. :(

**Comment by denfromufa** [comment]
then what is the purpose of pypkjs?

**Comment by Katharine** [comment]
pypkjs implements the PebbleKitJS runtime in javaScript. The emulator uses this to run javascript apps.

**Comment by denfromufa** [comment]
is it possible to use pypy.js, skulpt, brython, or pyjs to generate javascript code for pebble in python?

**Comment by youtux** [comment]
That sounds interesting, but I think you'd need to run the python->javascript compilation inside your project at build time, or just-in-time compile at runtime. The tools you described surely support just-in-time compilation on the browser, you "just" need to understand how to call them directly in javascript.
