### ISSUE TITLE
Bug: XMLHttpRequest doesn't work with https under python 2.7.9

### ISSUE THREAD

**Issue by youtux** [pebble/pypkjs#4]
After some troubleshooting I've found that connections made using https never gets a response.

Can you fix this?
Thanks!

**Comment by Katharine** [comment]
What version of python are you using?

**Comment by youtux** [comment]
2.7.9

**Comment by Katharine** [comment]
This is a [known issuse](https://developer.getpebble.com/sdk/changelogs/3.0-dp4/#known-issues) with python 2.7.8 and 2.7.9. We do not yet have a fix.

**Comment by youtux** [comment]
Oh I see.

**Comment by youtux** [comment]
It seems that ssl works with gevent/requests using [this fork](http://github.com/NextThought/gevent) for gevent.

Just need to install cython as well:

    pip install -U cython git+git://github.com/NextThought/gevent@8ac8febedfbb3afa5af9080af2c2f5b8d0283770#egg=gevent

Of course this is not the solution, but while we are waiting for gevent to update...

**Comment by Katharine** [comment]
Fixed.
